version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: deps
      prefix-development: deps
    groups:
      eslint:
        patterns:
          - eslint
          - "@eslint/*"
          - globals

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: actions
